# Generated by Django 5.0 on 2024-11-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
