# Generated by Django 5.0 on 2024-11-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='tags',
            new_name='links',
        ),
    ]
