# Generated by Django 5.0 on 2024-11-02 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_rename_tags_collection_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name="link",
            unique_together={("url", "user")},
        ),
    ]
